#version is integer from 0 to 255
library-version := {LIBVERSION}
#patchlevel is integer from 0 (from 1 if version is 0) to 255
library-patchlevel := {LIBPATCHLEVEL}
#revision is integer from 0 to 65535 and can be incremented everytime when version or patchlevel is changed
library-revision := {LIBREVISION}

dependency-libraries := {DEPENDENYLIBS}

#srcs := inputlinux.cc types.cc

#headers := 

include ../../../../auto/modrules.mk


