#'any' or set of items from list: linux, mswin, darwin, unix (any unix clone including linux and darwin), android?
bundle-platform := linux

#srcs := inputlinux.cc types.cc

#headers := 

include ../../../../auto/modrules.mk


