#version is integer from 0 to 255
library-version := 0
#patchlevel is integer from 0 (from 1 if version is 0) to 255
library-patchlevel := 2
#revision is integer from 0 to 65535 and can be incremented everytime when version or patchlevel is changed
library-revision := 2

#'any' or set of items from list: linux, mswin, darwin, unix (any unix clone including linux and darwin), android?
bundle-platform := linux

dependency-bundles := unet/types/di_toneplayer

#srcs := inputlinux.cc types.cc

#headers := 

include ../../../../auto/modrules.mk


